name: Build and Deploy to gh-pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prepare dist
        run: |
          mkdir -p dist
          shopt -s dotglob
          cp -r * dist/
          echo "Prepared dist with project files"
          cp dist/index.html dist/404.html || true
          touch dist/.nojekyll

      - name: Minify CSS
        run: |
          npx --yes csso-cli@5 dist/style.css --output dist/style.css || true

      - name: Minify JS (exclude sw.js, app.js)
        shell: bash
        run: |
          if compgen -G "dist/js/*.js" > /dev/null; then
            for f in dist/js/*.js; do
              echo "Minifying $f"
              npx --yes terser@5 "$f" --compress --mangle false --keep-fnames --output "$f" || true
            done
          fi

      - name: Minify HTML
        run: |
          npx --yes html-minifier-terser@7 \
            --collapse-whitespace \
            --remove-comments \
            --remove-redundant-attributes \
            --remove-script-type-attributes \
            --remove-style-link-type-attributes \
            --use-short-doctype \
            --minify-css true \
            --minify-js false \
            -o dist/index.html dist/index.html || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
